<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'BaseController' => $baseDir . '/app/controllers/BaseController.php',
    'BaseModel' => $baseDir . '/app/models/BaseModel.php',
    'CreatePostsTable' => $baseDir . '/app/database/migrations/2014_10_06_201826_create_posts_table.php',
    'CreateUsersAddressesTable' => $baseDir . '/app/database/migrations/2014_10_13_155746_create_usersAddresses_table.php',
    'CreateUsersPostsTable' => $baseDir . '/app/database/migrations/2014_10_13_160329_create_usersPosts_table.php',
    'CreateUsersTable' => $baseDir . '/app/database/migrations/2014_10_09_134658_create_users_table.php',
    'DatabaseSeeder' => $baseDir . '/app/database/seeds/DatabaseSeeder.php',
    'HomeController' => $baseDir . '/app/controllers/HomeController.php',
    'PortfolioController' => $baseDir . '/app/controllers/PortfolioController.php',
    'Post' => $baseDir . '/app/models/Post.php',
    'PostTableSeeder' => $baseDir . '/app/database/seeds/PostTableSeeder.php',
    'PostsController' => $baseDir . '/app/controllers/PostsController.php',
    'ResumeController' => $baseDir . '/app/controllers/ResumeController.php',
    'TestCase' => $baseDir . '/app/tests/TestCase.php',
    'User' => $baseDir . '/app/models/User.php',
    'UserTableSeeder' => $baseDir . '/app/database/seeds/UserTableSeeder.php',
);
